setup:
  project: "CardioRS/interpretability"
  name: ${experiment.experiment_kwargs.experiment_name}
  tags: ${experiment.experiment_kwargs.experiment_name}
neptune:
  tags: 'waifu-pilot'
  project: 'greggyfromtheblock/waif'
trainer:
  default_root_dir: "/home/ruyogagp/gan_results/waifu/"
  gpus: -1
  val_check_interval: 1.0
  fast_dev_run: False
  max_epochs: 50
  min_epochs: 50
  auto_lr_find: False
experiment:
  datamodule: WaifuDatamodule
  task: GAN
  monitor: 'generator_loss'
  datamodule_kwargs:
    folderpath: '/home/ruyogagp/gan/img_database/waifu'
    batch_size: 128
    image_size: 64
  generator_kwargs:
    latent_dim: 100
    featuremap_dim: 64
    output_dim: 3
  discriminator_kwargs:
    featuremap_dim: 64
    input_dim: 3